### ISSUE TITLE
Migration to organization

### ISSUE THREAD

**Issue by lbischof** [caddy-ansible/caddy-ansible#1]

**Comment by lbischof** [comment]
I created a namespace request for ansible-galaxy: https://github.com/ansible/galaxy/issues/2096

**Comment by joelnb** [comment]
I notice you updated everything to point to the organisation on Travis too. Nice work on that! I've gone ahead and created an issue to track getting the tests to pass reliably and I will have a go at solving the current issues there.

https://github.com/caddy-ansible/caddy-ansible/issues/2

**Comment by lbischof** [comment]
The Galaxy namespace has been created. I also updated the README
