### ISSUE TITLE
Cannot update caddy

### ISSUE THREAD

**Issue by paulfantom** [caddy-ansible/caddy-ansible#13]
[The link used to get all caddy releases](https://github.com/caddy-ansible/caddy-ansible/blob/master/tasks/main.yml#L20) went inactive. This causes the role to fail when using default setting of [`caddy_update: true`](https://github.com/caddy-ansible/caddy-ansible/blob/master/defaults/main.yml#L6).

**Comment by lbischof** [comment]
Thanks for reporting the issue. I created a PR.
