### ISSUE TITLE
Using this role fails because caddy repo changed

### ISSUE THREAD

**Issue by jeyemwey** [caddy-ansible/caddy-ansible#16]
When using the role, the provision fails. This is likely because caddy changed its repository:

```
TASK [caddy_ansible.caddy_ansible : Get all Caddy releases] ********************
fatal: [default]: FAILED! => {"changed": false, "dest": "/home/caddy/releases.txt", "elapsed": 0, "msg": "Request failed", "response": "HTTP Error 404: Not Found", "status_code": 404, "url": "https://api.github.com/repos/mholt/caddy/git/refs/tags"}
```

The underlying Github repo (mholt/caddy) does not exist anymore, since it was moved to https://github.com/caddyserver/caddy .

Therefore, the rest endpoint in `tasks/main.yml` must change to: https://api.github.com/repos/caddyserver/caddy/git/refs/tags

**Comment by lbischof** [comment]
Thanks for the bug report. It seems this change was already made last year: https://github.com/caddy-ansible/caddy-ansible/commit/0cbb0ed85ab6f2e1bea9983221b8a9996205c774 but without a new release.

I released a new version: https://github.com/caddy-ansible/caddy-ansible/releases and it should be available on Ansible Galaxy. Sorry for the inconvenience.

**Comment by jeyemwey** [comment]
Im glad that it was resolved so quickly, thanks :)
