### ISSUE TITLE
CADDYPATH removed in v2

### ISSUE THREAD

**Issue by Perflyst** [caddy-ansible/caddy-ansible#19]
CADDYPATH was removed in Caddy v2: https://caddyserver.com/docs/v2-upgrade#command-line

https://github.com/caddy-ansible/caddy-ansible/blob/master/templates/caddy.service#L30

Certificates and other stuff is now stored in the home folder
```bash
$ ls /home/caddy/.local/share/caddy/
acme  certificates  locks  ocsp
```

**Comment by Perflyst** [comment]
How do you want to proceed? Is .local in home "okay"? Do we want to map it somewhere else?

**Comment by lbischof** [comment]
Does something speak against leaving it in home? I think  if we don't have a reason to change it, we should leave it.

**Comment by Perflyst** [comment]
> Does something speak against leaving it in home?

I don't think so but it was moved to a different location back then with v1 so I wanted to ask first.
