### ISSUE TITLE
Fix travis tests

### ISSUE THREAD

**Issue by joelnb** [caddy-ansible/caddy-ansible#2]
Currently the tests are failing on Travis in this task:

```
TASK [caddy-ansible : Get all Caddy releases] **********************************
fatal: [jessie]: FAILED! => {"changed": false, "dest": "/home/caddy/releases.txt", "msg": "Request failed", "response": "HTTP Error 403: Forbidden", "state": "absent", "status_code": 403, "url": "https://api.github.com/repos/mholt/caddy/git/refs/tags"}
fatal: [centos7]: FAILED! => {"changed": false, "dest": "/home/caddy/releases.txt", "msg": "Request failed", "response": "HTTP Error 403: Forbidden", "state": "absent", "status_code": 403, "url": "https://api.github.com/repos/mholt/caddy/git/refs/tags"}
changed: [stretch]
changed: [xenial]
changed: [fedora]
```

I think this might be because the requests are being rate limited - I was able to reproduce this myself by simply running `watch -n 1 curl -sSL https://api.github.com/repos/mholt/caddy/git/refs/tags` for a little bit until I started getting 403 responses with this body:

```
{
  "message": "API rate limit exceeded for x.x.x.x. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)",
  "documentation_url": "https://developer.github.com/v3/#rate-limiting"
}
```

I don't think having to authenticate these requests would be a great solution so I will look for an alternate one.

**Comment by lbischof** [comment]
If it really is rate limiting then we could wait a little and retry like when downloading caddy:
```
  retries: 3
  delay: 2
```

**Comment by joelnb** [comment]
Yeah I think that is well worth adding but in this case I'm not sure it's quite that simple - the [current rate limits](https://developer.github.com/v3/#rate-limiting) seem to be 60 requests an hour for unauthenticated requests or 5000 for requests authenticated with a token.

If we assume that all the Travis runners are NATed behind a relatively small number of public IPs I can't see any situation where 60 requests an hour is going to be reliable - the tests for this module will run at least 10 requests to that endpoint for each test run (1 for each of the 5 tested OSes, then again when they rerun to check differences) so even supposing no other project makes any requests to Github from the same public IP we would only be able to support  6 test runs per hour. If anything else does hit Github on the same public IP then that could be 0 test runs an hour (don't see any way to predict) so it doesn't feel nice to me.

I have a branch where I added the ability to specify the Github OAuth token as I feel there is probably a usecase for this (e.g. someone wants to run this on 100 caddy servers NATed behind a single IP) but even then you have to resort to using [workarounds](https://fishi.devtail.io/weblog/2016/04/02/testing-ansible-ansible-vault-travis-ci/) I'm not keen on to provide that in the tests.

Currently I am actually working on some other issues I saw in the tests which led me to have a go at migrating to molecule 2 & then I will return to the issue with the rate limiting.

Interested in any thoughts you have on any of this though!

**Comment by joelnb** [comment]
Currently the tests are working well so I am going to close this. Because https://github.com/caddy-ansible/caddy-ansible/pull/6 contains support for providing a token to github if the rate-limiting becomes a problem in future we could provide a token to the Travis tests (this can be done using the encryption of secrets that Travis provides to avoid leaking).
