### ISSUE TITLE
Add example with file lookups

### ISSUE THREAD

**Issue by lbischof** [caddy-ansible/caddy-ansible#25]
We should add an example of [file lookup](https://docs.ansible.com/ansible/latest/plugins/lookup.html#using-lookup-plugins) to the readme in case someone would prefer to have the Caddy config as a file.

**Comment by Perflyst** [comment]
It's already there or am I missing something? https://github.com/caddy-ansible/caddy-ansible#the-caddyfile


```
If you wish to use a template for the config you can do this:

caddy_config: "{{ lookup('template', 'templates/Caddyfile.j2') }}"

**Comment by lbischof** [comment]
Oops :+1:
