### ISSUE TITLE
Systemd version determination fails on Ubuntu 20.04

### ISSUE THREAD

**Issue by mikemccllstr** [caddy-ansible/caddy-ansible#29]
I am using the caddy-ansible role to install caddy on Ubuntu 20.04. Ubuntu 20.04 has systemd version 245.

I noticed that the generated caddy.service file has the StartLimitInterval and StartLimitBurst values in the Service section. Based on the logic in the caddy.service template, I would only expect these values in that section when caddy_systemd_version is < 230.

I ran ansible with verbose logging, and I noticed that it seems to pick up the apt package value instead of the pure version number:

```
TASK [caddy_ansible.caddy_ansible : Set systemd version fact] ******************
task path: /home/mike/.ansible/roles/caddy_ansible.caddy_ansible/tasks/preflight.yml:15
ok: [lab1.ipa3.mccllstr.net] => {
    "ansible_facts": {
        "caddy_systemd_version": "(245.4-4ubuntu3.6)"
    },
    "changed": false
}
```

I think this is because `systemctl --version` returns this on Ubuntu 20.04: `systemd 245 (245.4-4ubuntu3.6)`, and the preflight.yml file is picking up "(245.4-4ubuntu3.6)" instead of "245".

**Comment by joelnb** [comment]
Thanks for the report. We do have automated tests which include running on Ubuntu 20.04 so as well as looking into a solution I will try to work out why they didn't catch this error.
