### ISSUE TITLE
Release?

### ISSUE THREAD

**Issue by paulfantom** [caddy-ansible/caddy-ansible#3]
While creating prometheus demo site (https://github.com/prometheus/demo-site) We hit an issue when using ansible 2.9 with this role installed via ansible-galaxy.

Issue was solved 3 months ago with https://github.com/caddy-ansible/caddy-ansible/commit/325e584621e19016420b565676a9c748c16f8a43 but since there was no release with that commit, ansible-galaxy doesn't serve fixed version. Could there be a new release so the issue is gone?

**Comment by lbischof** [comment]
Version v2.1.1 released
