### ISSUE TITLE
Configurable caddy.service name

### ISSUE THREAD

**Issue by abstractvector** [caddy-ansible/caddy-ansible#33]
Would it be possible to add the caddy service name as a variable, e.g. `caddy_service_name: caddy.service`? My use case is wanting to run multiple caddy servers on a single host and have them not conflict with one another. This is the only conflict I have.

**Comment by lbischof** [comment]
Sure! I don't currently have time to make the change, but PRs are always welcome. The change should be small and backward compatible.
