### ISSUE TITLE
How to specify the version I prefer to use?

### ISSUE THREAD

**Issue by tom10271** [caddy-ansible/caddy-ansible#41]
Recently Caddy has a new release broken our application. We want to stablize it by specifying the version we prefer to use.

Disable update won't help.

**Comment by joelnb** [comment]
Do you just want to use a release from the caddy github? If so it is not possible right now but could be added - I think it would just involve allowing you to specify `caddy_version` yourself (currently it's always worked out from the available releases).

**Comment by stevenengland** [comment]
👍🏻 
I would love to specify a target version as well.

**Comment by joelnb** [comment]
So what I said above about just using releases from github would work for you? I don't think it's too hard to add so I'm happy to do it if so. The limitation here is that those releases have no plugins so if you need plugins you will still be unable to specify a version (I would probably make things fail in this case so it is clear the version cannot be honoured).

**Comment by stevenengland** [comment]
> I have done some work on this over in https://github.com/caddy-ansible/caddy-ansible/pull/59 if anyone has a chance to test. I'll aim to put the finishing touches on it before long & go ahead with the merge (mainly just need to add to the README).

I would love to do so but I am off for a while :-)

**Comment by marcossantiago** [comment]
Hey @joelnb, 

Thanks for the work!

I have just tested using a different version than the latest and it works fine. The latest version is 2.6.4 and was able to install version 2.6.3 successfully.


```
caddy_version: 2.6.3
...

$ caddy version
v2.6.3 h1:QRVBNIqfpqZ1eJacY44I6eUC1OcxQ8D04EKImzpj7S8=

```
