### ISSUE TITLE
v2 support ?

### ISSUE THREAD

**Issue by rgarrigue** [caddy-ansible/caddy-ansible#5]
Hi there

Now that Caddy v2 is out, wanted to know, does this role support v2 ? I guess so, but might want to add a word about v1 / v2 support in the README.

Best regards,

**Comment by joelnb** [comment]
Hi @rgarrigue thanks for your suggestion. Currently this role actually does not have support for caddy v2. I keep meaning to upgrade my hosts so I will try to get around to that before too long and try to get at least some initial support merged here when I do so.

If you have any particular suggestions where it might be good for this role to work differently between v1 and v2 I would be very interested to hear them.

**Comment by rgarrigue** [comment]
Hmm... I've been reading quickly the role, I must say I'm impressed by the quality. Congratulations, really.

So no real "hard" advice here. I may have 2 suggestions

- Configuration wise, json becames a first class citizen for Caddy v2. You might want to rely on a dict for caddy_config, and a `| to_nice_json` filter. Here' an example https://github.com/cloudalchemy/ansible-prometheus/blob/master/tasks/configure.yml#L39-L44
- Rename your default molecule scenario to v1, add a v2, add a `molecule test --all` to your CI.

**Comment by SuperQ** [comment]
It looks like Caddy v1 downloading is now broken.

**Comment by jgeusebroek** [comment]
> It looks like Caddy v1 downloading is now broken.

Yes, it is unfortunately.

**Comment by joelnb** [comment]
This should now be addressed by https://github.com/caddy-ansible/caddy-ansible/pull/6 and I am successfully using this role with Caddy on some of my systems. Any testing other people are able to do would be much appreciated (as ever).

**Comment by jgeusebroek** [comment]
Looks good! Now to convert my config to the new format.

**Comment by SuperQ** [comment]
I think we also need to publish a new release tag for Ansible Galaxy to pick it up. Probably should have a major version bump.

**Comment by joelnb** [comment]
Thanks for letting me know. I've not previously done a release on this repo but I created the tag and the release in Github and all seems to have worked nicely on the Ansible Galaxy side.

The new release is [v3.0.0](https://github.com/caddy-ansible/caddy-ansible/releases/tag/v3.0.0).
