### ISSUE TITLE
Retain existing /etc/caddy/Caddyfile

### ISSUE THREAD

**Issue by citizenrich** [caddy-ansible/caddy-ansible#54]
Hi, thanks for this awesome Ansible role. I noticed in subsequent runs that it overwrites the Caddyfile at /etc/caddy/Caddyfile. Is there a flag to retain the file if it already exists?

**Comment by joelnb** [comment]
Currently this is not possible & it is not something I would ever do. That said I am happy to add the functionality as long as it is not enabled by default. I'll make a PR.

**Comment by joelnb** [comment]
I believe what I have done should solve your issue here but let me know if not. Just ensure you are using the latest version of the role and set `caddy_config_update: false`.

**Comment by citizenrich** [comment]
Awesome, thanks. Works perfectly.

<img width="487" alt="Screen Shot 2022-11-16 at 12 11 00" src="https://user-images.githubusercontent.com/2528387/202247459-dafd64eb-37d0-4133-bf79-051144f80057.png">
